import sys

def fb(lines):
    """ (filename) -> print
    Write a program that prints out the the pattern generated by such a 
    scenario given the values of 'A'/'B' and 'N' which are read from an 
    input text file. The input text file contains three space delimited 
    numbers i.e. A, B, N. The program should then print out the final series 
    of numbers using 'F' for fizz, 'B' for 'buzz' and 'FB' for fizz buzz.
    """
    sl = lines.split()
    nl = map(int, sl)
    i = 0
    while i < len(nl):
        loop = nl[i:i+3]
        for j in range(1,loop[2]+1):
            print (not j % loop[0])*'F' + (not j % loop[1])*'B' or j,
        i = i + 3
        print

test_cases = open(sys.argv[1], 'r')
for test in test_cases:
    fb(test)
test_cases.close()



